[toolchain]
anchor_version = "0.31.0"

[features]
resolution = true
skip-lint = true

[programs.devnet]
LoyaltyProgram = "24rAgLg6RkxhkrS6rp9N7cTZC1GJuembSxha5gJd81tL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "DevNet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/jest --preset ts-jest"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899
